// ─── Monde Tour Resort — Seed Data ───
// This data is loaded into localStorage on first visit.
// Admin panel edits update this localStorage copy.

const defaultData = {
  settings: {
    siteName: "Monde Tour",
    tagline: "Байгальтай ойрхон, тав тухтай амралтыг танд",
    phone: "+976 9911 2233",
    email: "info@mondetour.mn",
    address: "Тэрэлж, Говьсүмбэр аймаг, Монгол",
    facebook: "https://facebook.com/mondetour",
    instagram: "https://instagram.com/mondetour",
    mapEmbed: "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2624.9916256937604!2d107.430995!3d47.89437!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0x0!2zNDfCsDUzJzM5LjciTiAxMDfCsDI1JzUxLjYiRQ!5e0!3m2!1sen!2smn!4v1699999999999!5m2!1sen!2smn",
    mapLink: "https://maps.google.com/?q=47.894370,107.430995",
    businessHours: "24 цагаар (24/7)",
    seoTitle: "Monde Tour — Тэрэлж дэх байгалийн амралтын газар",
    seoDescription: "Monde Tour амралтын газар: гэр бааз, өрөө, хоол, багц, хурим, багийн бүтээлч ажил, гэр бүлийн баяр. Тэрэлж, Монгол.",
    lang: "mn"
  },

  users: [],
  currentUser: null,

  rooms: [
    {
      id: "room-1",
      name: "Стандарт гэр",
      capacity: 2,
      beds: "1 том ор",
      price: 180000,
      priceUnit: "өдөр",
      shortDesc: "Уламжлалт гэрт орчин үеийн тав тухыг хослуулсан өрөө.",
      description: "Монгол гэрийн уламжлалт загварыг орчин үеийн тав тухтай хослуулсан стандарт гэр. Дотор талдаа дулаахан, цэвэрхэн бөгөөд байгалийн үзэсгэлэнт харагдах цонхтой. Хосууд болон ганцаараа аялагчдад тохиромжтой.",
      facilities: ["Дулаахан хөнжил", "Хувийн ариун цэврийн өрөө", "Wifi", "Усан халаагч", "Цэвэрлэгээ", "Хөгжмийн систем"],
      images: ["images/camp-gers.jpg", "images/camp-overview.jpg", "images/camp-entrance.jpg"],
      featured: true
    },
    {
      id: "room-2",
      name: "Гэр бүлийн гэр",
      capacity: 5,
      beds: "1 том ор + 1 нэмэлт ор",
      price: 320000,
      priceUnit: "өдөр",
      shortDesc: "Гэр бүл, найз нөхдийн хамт амрахад зориулсан өргөн гэр.",
      description: "Гэр бүл, найз нөхөдтэйгээ хамт амрахад идеал. Өргөн талбай, нэмэлт ор, хүүхдэд ээлтэй орчинтой. Гадаа талбайд гал тогоо, суудалтай.",
      facilities: ["5 хүний багтаамж", "Хувийн ариун цэврийн өрөө", "Wifi", "Хөргөгч", "Цай, кофе", "Гадаа суудал"],
      images: ["images/camp-overview.jpg", "images/camp-gers.jpg", "images/camp-entrance.jpg"],
      featured: true
    },
    {
      id: "room-3",
      name: "VIP байшин",
      capacity: 4,
      beds: "2 том ор",
      price: 450000,
      priceUnit: "өдөр",
      shortDesc: "Премиум тав тух, өргөн талбай, байгалийн сайхан үзэмж.",
      description: "Модон байшинд бүрэн тохижуулсан VIP өрөө. Өргөн талбай, том цонх, байгалийн үзэсгэлэнт харагдах тагтантай. Онцгой амралт хайгчдад зориулав.",
      facilities: ["Тагтан", "Жакузи", "Мини бар", "Wifi", "Кондиционер", "Өглөөний цай", "Хувийн зоогийн өрөө"],
      images: ["images/camp-entrance.jpg", "images/camp-overview.jpg", "images/camp-gers.jpg"],
      featured: true
    },
    {
      id: "room-4",
      name: "Хамтын өрөө",
      capacity: 8,
      beds: "4 давхар ор",
      price: 280000,
      priceUnit: "өдөр",
      shortDesc: "Залуус, багийн аялалд зориулсан хямд өрөө.",
      description: "Залуус, дунд сургуулийн анги, багаар аялагчдад зориулсан хамтын өрөө. Цэвэрхэн, аюулгүй, эдийн засгийн хувьд хэмнэлттэй сонголт.",
      facilities: ["8 хүний багтаамж", "Хамтын ариун цэврийн өрөө", "Wifi", "Хөргөгч", "Хувцасны шүүгээ", "Тоглоомын тавцан"],
      images: ["images/camp-overview.jpg", "images/camp-gers.jpg"],
      featured: false
    }
  ],

  packages: [
    {
      id: "pkg-1",
      name: "Гэр бүлийн багц",
      people: "2-5 хүн",
      duration: "1 хоног",
      price: 520000,
      priceUnit: "багц",
      type: "family",
      shortDesc: "Гэр бүлээрээ амрах бүрэн багц: өрөө, хоол, үйлчилгээ багтсан.",
      description: "Гэр бүлээрээ чөлөөт цагийг үр дүнтэй өнгөрүүлэхэд зориулсан бүрэн багц. Өглөө, өдөр, оройн хоол, байгальтай танилцах аялал, хүүхдийн тоглоомын талбай багтсан.",
      includes: ["Гэр бүлийн гэр 1 шөнийн түрээс", "Өглөө, өдөр, оройн хоол", "Байгальтай танилцах аялал", "Хүүхдийн тоглоомын талбай", "Галын түүдэг", "Wifi"],
      image: "images/camp-overview.jpg",
      featured: true
    },
    {
      id: "pkg-2",
      name: "Хосуудын романтик багц",
      people: "2 хүн",
      duration: "1 хоног",
      price: 420000,
      priceUnit: "багц",
      type: "couple",
      shortDesc: "Хосуудын амралт, романтик орчин, онцгой үйлчилгээ.",
      description: "Хосуудын амралт, төрсөн өдөр, гэрлэлтийн ойн баярт зориулсан романтик багц. Оройн үдэшлэг, мөнгөн гэрэлтүүлэг, онцгой хоолны цэс багтсан.",
      includes: ["Стандарт гэр 1 шөнийн түрээс", "Романтик оройн хоол", "Өглөөний цай", "Мөнгөн гэрэлтүүлэг", "Цэцгэн баглаа", "Wifi"],
      image: "images/camp-gers.jpg",
      featured: true
    },
    {
      id: "pkg-3",
      name: "Байгууллагын Team Building",
      people: "10-50 хүн",
      duration: "1-2 хоног",
      price: 150000,
      priceUnit: "хүн/өдөр",
      type: "corporate",
      shortDesc: "Багийн бүтээлч ажил, уулзалт, хөгжөөнт тоглоом багтсан.",
      description: "Байгууллагын баг хамт олныг бэхжүүлэх, урам зориг өгөх team building багц. Уулзалтын өрөө, хөгжөөнт тоглоом, хоол, байр, хөтөлбөр багтсан.",
      includes: ["Байрны тохиргоо", "Уулзалтын өрөө", "Хөгжөөнт тоглоомууд", "Бүх хоол", "Автобус зохион байгуулалт", "Event coordinator"],
      image: "images/camp-entrance.jpg",
      featured: true
    },
    {
      id: "pkg-4",
      name: "Хуримын event багц",
      people: "20-120 хүн",
      duration: "1-2 хоног",
      price: 0,
      priceUnit: "захиалгаар",
      type: "event",
      shortDesc: "Хурим, томоохон баярын арга хэмжээнд зориулсан багц.",
      description: "Хурим, хүрэлцэн ирсэн зочдын баяр, төрсөн өдрийн томоохон арга хэмжээнд зориулсан бүрэн багц. Зоог, чимэглэл, хөгжим, байр, зургийн багц гэх мэт.",
      includes: ["Хуримын талбай", "Зоогийн үйлчилгээ", "Чимэглэлийн сонголт", "Хөгжмийн систем", "Зочдын байр", "Event coordinator", "Зургийн багц"],
      image: "images/camp-overview.jpg",
      featured: false
    }
  ],

  menu: {
    categories: [
      { id: "breakfast", name: "Өглөөний цай" },
      { id: "lunch", name: "Өдрийн хоол" },
      { id: "dinner", name: "Оройн хоол" },
      { id: "traditional", name: "Уламжлалт хоол" },
      { id: "beverages", name: "Ундаа" }
    ],
    items: [
      { id: "m-1", category: "breakfast", name: "Сүүтэй будаа", description: "Уламжлалт монгол өглөөний цай", price: 12000 },
      { id: "m-2", category: "breakfast", name: "Боорцог", description: "Гэрийн нөхцөлд хийсэн шүүсэн боорцог", price: 8000 },
      { id: "m-3", category: "breakfast", name: "Өндөг, талх, цай", description: "Өглөөний хөнгөн сет", price: 15000 },
      { id: "m-4", category: "lunch", name: "Хорхог", description: "Чулуун дотор хийсэн уламжлалт хорхог", price: 45000 },
      { id: "m-5", category: "lunch", name: "Гуляш", description: "Махан гуляш шарсан төмстэй", price: 28000 },
      { id: "m-6", category: "lunch", name: "Будаа, шөл", description: "Уламжлалт хоолны сет", price: 22000 },
      { id: "m-7", category: "dinner", name: "Нарийн махан хуурга", description: "Нарийн махан хуурга, ногооны хольцтой", price: 35000 },
      { id: "m-8", category: "dinner", name: "Шарсан загас", description: "Сүүлийн шарсан загас, ногоотой", price: 32000 },
      { id: "m-9", category: "traditional", name: "Цуйван", description: "Гоймонтой цуйван", price: 20000 },
      { id: "m-10", category: "traditional", name: "Бууз", description: "Монгол гэрийн бууз", price: 18000 },
      { id: "m-11", category: "beverages", name: "Салхины цай", description: "Улаан цай, сүү", price: 5000 },
      { id: "m-12", category: "beverages", name: "Кофе", description: "Американо, латте", price: 7000 }
    ]
  },

  events: [
    {
      id: "evt-1",
      category: "corporate",
      title: "Байгууллагын team building",
      description: "Багийн бүтээлч ажил, уулзалт, хөгжөөнт тоглоом, хоол, байр багтсан бүрэн багц.",
      features: ["10-120 хүртэлх хүний багтаамж", "Уулзалтын өрөө", "Спорт талбай", "Хөгжөөнт тоглоом", "Бүх хоол", "Event coordinator"],
      image: "images/camp-entrance.jpg"
    },
    {
      id: "evt-2",
      category: "wedding",
      title: "Хуримын арга хэмжээ",
      description: "Байгалийн сайхан үзэмж, том талбай, зоогийн үйлчилгээ бүхий хуримын төлөвлөлт.",
      features: ["120 хүртэлх зочин", "Хуримын талбай", "Зоогийн үйлчилгээ", "Чимэглэл", "Хөгжим, гэрэлтүүлэг", "Зургийн багц"],
      image: "images/camp-overview.jpg"
    },
    {
      id: "evt-3",
      category: "family",
      title: "Гэр бүлийн баяр",
      description: "Төрсөн өдөр, ойн баяр, гэр бүлийн уулзалт зэрэг дотно арга хэмжээнд зориулсан.",
      features: ["20-60 хүний багтаамж", "Хувийн талбай", "Төрсөн өдрийн чимэглэл", "Хоолны сонголт", "Хүүхдийн тоглоомын талбай", "Галын түүдэг"],
      image: "images/camp-gers.jpg"
    }
  ],

  gallery: [
    { id: "g-1", category: "nature", src: "images/hero-nature.jpg", title: "Монголын ногоон талбай" },
    { id: "g-2", category: "nature", src: "images/mongolia-horse.jpg", title: "Морьтон малчид" },
    { id: "g-3", category: "nature", src: "images/mongolian-steppes.jpg", title: "Өргөн тал нутаг" },
    { id: "g-4", category: "nature", src: "images/terelj-steppe.jpg", title: "Тэрэлжийн тал" },
    { id: "g-5", category: "nature", src: "images/terelj-horse.jpg", title: "Тэрэлжийн адуун сүрэг" },
    { id: "g-6", category: "nature", src: "images/terelj-skies.jpg", title: "Тэрэлжийн тэнгэр" },
    { id: "g-7", category: "rooms", src: "images/camp-gers.jpg", title: "Монгол гэр" },
    { id: "g-8", category: "resort", src: "images/camp-overview.jpg", title: "Баазын бүрэн харагдац" }
  ],

  bookings: [],

  pages: {
    about: {
      title: "Бидний тухай",
      titleEn: "About Us",
      content: "Monde Tour нь Тэрэлжийн байгалийн үзэсгэлэн бүрдэл дунд орших тав тухтай амралтын газар юм. Бид байгальтай ойрхон, орчин үеийн үйлчилгээтэй, уламжлалт зочломтгой Монгол соёлыг хослуулсан амралтын туршлагыг санал болгодог. Гэр бүл, хосууд, найз нөхөд, байгууллагын баг бүрт тохирсон өрөө, багц, хоол, event үйлчилгээгээс сонгоорой.",
      contentEn: "Monde Tour is a comfortable resort located in the scenic Terelj area. We offer a nature-close experience that blends modern services with traditional Mongolian hospitality. Choose from rooms, packages, dining, and event services tailored for families, couples, friends, and corporate groups."
    },
    location: {
      content: "Улаанбаатар хотоос 58 км зайд, Тэрэлжийн үзэсгэлэнт хөндийд байрладаг. Замын хөдөлгөөн харьцангуй чөлөөтэй, машинаар 1-1.5 цаг явна.",
      contentEn: "Located 58 km from Ulaanbaatar in the scenic Terelj valley. Traffic is usually light, and the drive takes about 1–1.5 hours by car."
    }
  },

  eventsEn: [
    {
      id: "evt-1",
      category: "corporate",
      title: "Team Building & Corporate Events",
      description: "Full-service packages for team building, meetings, company celebrations, and presentations.",
      features: ["Capacity 10–120 people", "Meeting rooms", "Sports grounds", "Fun games & program", "All meals & drinks", "Event coordinator"]
    },
    {
      id: "evt-2",
      category: "wedding",
      title: "Wedding Events",
      description: "Plan your wedding with beautiful nature, large venue space, and full catering service.",
      features: ["Up to 120 guests", "Wedding venue", "Catering service", "Decoration options", "Music & lighting", "Photo package"]
    },
    {
      id: "evt-3",
      category: "family",
      title: "Family Celebrations",
      description: "Perfect for birthdays, anniversaries, and intimate family gatherings.",
      features: ["Capacity 20–60 people", "Private area", "Birthday decoration", "Food options", "Kids play area", "Bonfire"]
    }
  ],

  i18n: {
    mn: {
      nav_home: "Нүүр",
      nav_about: "Бидний тухай",
      nav_rooms: "Байрлах өрөө",
      nav_food: "Хоолны үйлчилгээ",
      nav_packages: "Багц",
      nav_events: "Арга хэмжээ",
      nav_gallery: "Зургийн цомог",
      nav_contact: "Холбогдох",
      nav_my_bookings: "Миний захиалгууд",
      profile: "Профайл",
      login: "Нэвтрэх",
      logout: "Гарах",
      register: "Бүртгүүлэх",
      book_now: "Захиалга өгөх",
      view_packages: "Багц үзэх",
      learn_more: "Дэлгэрэнгүй",
      book: "Захиалах",
      contact_us: "Холбогдох",
      phone: "Утас",
      email: "Имэйл",
      address: "Хаяг",
      name: "Нэр",
      password: "Нууц үг",
      confirm_password: "Нууц үг давтах",
      submit: "Илгээх",
      booking_request: "Захиалгын хүсэлт",
      my_bookings_title: "Миний захиалгууд",
      no_bookings: "Одоогоор захиалга байхгүй.",
      booking_saved: "Таны захиалгын хүсэлтийг хүлээн авлаа. Манай ажилтан тантай удахгүй холбогдоно.",
      login_required: "Захиалга өгөхийн тулд эхлээд нэвтэрнэ үү.",
      welcome: "Тавтай морил",
      have_account: "Бүртгэлтэй юу? Нэвтрэх",
      no_account: "Бүртгэлгүй юу? Бүртгүүлэх",
      hero_tagline: "Байгальтай ойрхон, тав тухтай амралтыг танд",
      service_rooms: "Байрлах өрөө",
      service_food: "Хоолны үйлчилгээ",
      service_packages: "Багц",
      service_events: "Арга хэмжээ",
      intro_label: "Танилцуулга",
      intro_title: "Байгаль дундах тав тухтай амралт",
      intro_text: "Monde Tour нь Тэрэлжийн өвслөг толгод, цэвэр агаар дунд байрлах орчин үеийн амралтын газар юм. Бид уламжлалт Монгол гэрийн дулаахан орчин, орчин үеийн үйлчилгээг хослуулан, гэр бүл, хосууд, найз нөхөд, байгууллагын баг бүрт зориулсан тав тухтай амралтын туршлагыг бүрдүүлдэг.",
      services_label: "Үйлчилгээ",
      services_title: "Бид юу санал болгодог вэ?",
      services_desc: "Амралт, хоол, event — бүгдийг нэг дороос",
      service_rooms_desc: "Гэр, байшин, хамтын өрөөний сонголт",
      service_food_desc: "Уламжлалт хорхог, орчин үеийн цэс",
      service_packages_desc: "Гэр бүл, хос, байгууллагад зориулсан",
      service_events_desc: "Хурим, team building, баярын арга хэмжээ",
      view_all_packages: "Бүх багц харах",
      packages_label: "Багцууд",
      packages_title: "Онцлох багцууд",
      packages_desc: "Хамгийн их захиалагддаг, хамгийн тохиромжтой сонголтууд",
      view_all_rooms: "Бүх өрөө харах",
      rooms_label: "Өрөө",
      rooms_title: "Онцлох өрөөнүүд",
      rooms_desc: "Байгаль дундах тав тухтай унтлагын өрөө",
      events_label: "Event",
      events_title: "Арга хэмжээ зохион байгуулах",
      events_desc: "Байгууллагын уулзалтаас эхлээд хурим хүртэл — бид тусална",
      gallery_title: "Monde Tour-ийн дүр төрх",
      gallery_desc: "Байгаль, өрөө, хоол, event-ийн онцлох зургууд",
      view_all_gallery: "Бүх зураг үзэх",
      location_title: "Байршил",
      location_find_title: "Тэрэлжид биднийг олоорой",
      location_text: "Улаанбаатараас 58 км зайд, Тэрэлжийн байгалийн үзэсгэлэн бүрдэл дунд байрладаг. Замын хөдөлгөөн харьцангуй чөлөөтэй бөгөөд машинаар ойролцоогоор 1-1.5 цаг явна.",
      location_desc: "Улаанбаатараас 58 км зайд, Тэрэлжийн байгалийн үзэсгэлэн бүрдэл дунд байрладаг.",
      philosophy_label: "Үзэл баримтлал",
      philosophy_title: "Бид яагаад онцгой вэ?",
      directions: "Чиглэл авах",
      coordinates: "Координат",
      contact_title: "Холбогдох",
      contact_subtitle: "Бидэнтэй холбогдож, таны аяллын төлөвлөгөөг хамтран бүтээгээрэй",
      send_message: "Мессеж илгээх",
      your_name: "Таны нэр",
      your_email: "Имэйл хаяг",
      your_message: "Мессеж",
      message_sent: "Мессеж илгээгдлээ. Баярлалаа!",
      follow_us: "Биднийг дагах",
      quick_links: "Холбоосууд",
      newsletter: "Мэдээлэл хүлээн авах",
      subscribe: "Бүртгүүлэх",
      gallery: "Зургийн цомог",
      view_map: "Газрын зураг үзэх",
      rooms_page_title: "Байрлах өрөө",
      rooms_page_desc: "Байгаль дундах тав тухтай унтлагын өрөөний сонголт",
      all_rooms: "Бүх өрөө",
      filter_rooms: "Өрөө шүүх",
      sort_by: "Эрэмбэлэх",
      no_rooms: "Өрөө олдсонгүй.",
      capacity: "Багтаамж",
      beds: "Ор",
      amenities: "Тавилга",
      price_per_night: "Нэг шөнийн үнэ",
      price_per_person: "Нэг хүний үнэ",
      night: "шөнө",
      person: "хүн",
      people: "Хүний тоо",
      details: "Дэлгэрэнгүй",
      room_detail_title: "Өрөөний дэлгэрэнгүй",
      room_detail_desc: "Өрөөний мэдээлэл, үнэ, боломжууд",
      book_this_room: "Энэ өрөөг захиалах",
      gallery_room: "Өрөөний зургууд",
      food_page_title: "Хоолны үйлчилгээ",
      food_page_desc: "Уламжлалт Монгол хоол, орчин үеийн цэс",
      menu: "Цэс",
      menu_category_all: "Бүгд",
      menu_category_mongolian: "Монгол хоол",
      menu_category_bbq: "BBQ",
      menu_category_beverage: "Уух зүйлс",
      menu_category_dessert: "Амттан",
      ingredients: "Орц",
      portion: "Порц",
      packages_page_title: "Багцууд",
      packages_page_desc: "Гэр бүл, хосууд, байгууллагад зориулсан багцууд",
      all_packages: "Бүх багц",
      duration: "Хугацаа",
      days: "хоног",
      package_detail_title: "Багцын дэлгэрэнгүй",
      package_detail_desc: "Багцын хөтөлбөр, үнэ, багтаамж",
      includes: "Багтсан зүйлс",
      itinerary: "Хөтөлбөр",
      book_this_package: "Энэ багцыг захиалах",
      gallery_page_title: "Зургийн цомог",
      gallery_page_desc: "Байгаль, өрөө, хоол, event-ийн онцлох зургууд",
      all_photos: "Бүх зураг",
      category_nature: "Байгаль",
      category_rooms: "Өрөө",
      category_food: "Хоол",
      category_events: "Арга хэмжээ",
      category_people: "Хүмүүс",
      contact_page_title: "Холбогдох",
      contact_page_desc: "Бидэнтэй холбогдож, таны аяллын төлөвлөгөөг хамтран бүтээгээрэй",
      get_in_touch: "Холбогдох",
      contact_info: "Холбоо барих мэдээлэл",
      opening_hours: "Ажлын цаг",
      open_daily: "Өдөр бүр 08:00 - 22:00",
      booking_page_title: "Захиалга",
      booking_page_desc: "Өрөө, багц, event үйлчилгээг онлайнаар захиалах",
      select_service: "Үйлчилгээ сонгох",
      arrival_date: "Ирэх огноо",
      departure_date: "Гарах огноо",
      select_room: "Өрөө сонгох",
      select_package: "Багц сонгох",
      notes: "Нэмэлт мэдээлэл",
      your_request: "Таны хүсэлт",
      my_bookings_page_title: "Миний захиалгууд",
      my_bookings_page_desc: "Таны өмнөх болон идэвхитэй захиалгууд",
      booking_date: "Захиалгын огноо",
      booking_status: "Төлөв",
      auth_page_title: "Нэвтрэх / Бүртгүүлэх",
      auth_page_desc: "Профайлаа удирдаж, захиалгаа хянах",
      phone_registered: "Энэ утасны дугаар бүртгэлтэй байна.",
      invalid_credentials: "Утас эсвэл нууц үг буруу байна.",
      password_mismatch: "Нууц үг таарахгүй байна.",
      services: "Үйлчилгээ",
      corporate_events: "Байгууллагын арга хэмжээ",
      weddings: "Хурим",
      family_celebrations: "Гэр бүлийн баяр",
      rights_reserved: "Бүх эрх хуулиар хамгаалагдсан",
      admin: "Admin",
      close: "Хаах",
      menu_open: "Цэс нээх",
      menu_close: "Цэс хаах",
      admin_dashboard: "Хяналтын самбар",
      admin_bookings: "Захиалгууд",
      admin_rooms: "Өрөө",
      admin_packages: "Багц",
      admin_menu: "Меню",
      admin_events: "Event",
      admin_gallery: "Зургийн цомог",
      admin_settings: "Тохиргоо",
      back_to_site: "Вэб рүү буцах",
      admin_login_title: "Monde Tour Admin",
      admin_login_desc: "Нэвтрэх мэдээллээ оруулна уу",
      admin_password: "Нууц үг",
      admin_default_password: "Анхны нууц үг",
      admin_total_rooms: "Нийт өрөө",
      admin_total_packages: "Нийт багц",
      admin_new_bookings: "Шинэ захиалга",
      admin_total_bookings: "Нийт захиалга",
      admin_recent_bookings: "Сүүлийн захиалгууд",
      admin_all_bookings: "Бүх захиалгын хүсэлт",
      admin_room_list: "Өрөөний жагсаалт",
      admin_add_room: "Өрөө нэмэх",
      admin_package_list: "Багцын жагсаалт",
      admin_add_package: "Багц нэмэх",
      admin_menu_list: "Меню",
      admin_add_menu: "Хоол нэмэх",
      admin_event_list: "Event-ийн жагсаалт",
      admin_add_event: "Event нэмэх",
      admin_gallery_list: "Зургийн цомог",
      admin_add_gallery: "Зураг нэмэх",
      admin_general_settings: "Ерөнхий тохиргоо",
      admin_save: "Хадгалах",
      admin_reset_data: "Өгөгдлийг анхны байдалд авах",
      admin_no_bookings: "Одоогоор захиалга байхгүй.",
      admin_status_updated: "Төлөв шинэчлэгдлээ.",
      admin_room_saved: "Өрөө хадгалагдлаа.",
      admin_room_deleted: "Өрөө устгагдлаа.",
      admin_package_saved: "Багц хадгалагдлаа.",
      admin_package_deleted: "Багц устгагдлаа.",
      admin_menu_saved: "Меню хадгалагдлаа.",
      admin_menu_deleted: "Хоол устгагдлаа.",
      admin_event_saved: "Event хадгалагдлаа.",
      admin_event_deleted: "Event устгагдлаа.",
      admin_gallery_saved: "Зураг хадгалагдлаа.",
      admin_gallery_deleted: "Зураг устгагдлаа.",
      admin_settings_saved: "Тохиргоо хадгалагдлаа.",
      admin_delete_room_confirm: "Энэ өрөөг устгах уу?",
      admin_delete_package_confirm: "Энэ багцыг устгах уу?",
      admin_delete_menu_confirm: "Энэ хоолыг устгах уу?",
      admin_delete_event_confirm: "Энэ event-ийг устгах уу?",
      admin_delete_gallery_confirm: "Энэ зургийг устгах уу?",
      admin_edit_room: "Өрөө засах",
      admin_add_room_title: "Шинэ өрөө нэмэх",
      admin_edit_package: "Багц засах",
      admin_add_package_title: "Шинэ багц нэмэх",
      admin_edit_menu: "Хоол засах",
      admin_add_menu_title: "Шинэ хоол нэмэх",
      admin_edit_event: "Event засах",
      admin_add_event_title: "Шинэ event нэмэх",
      admin_edit_gallery: "Зураг засах",
      admin_add_gallery_title: "Шинэ зураг нэмэх",
      admin_delete: "Устгах",
      edit: "Засах",
      featured: "Онцлох",
      cancel: "Болих",
      save: "Хадгалах",
      type: "Төрөл",
      category: "Ангилал",
      description: "Тайлбар",
      title: "Гарчиг",
      image: "Зураг"
    },
    en: {
      nav_home: "Home",
      nav_about: "About",
      nav_rooms: "Rooms",
      nav_food: "Dining",
      nav_packages: "Packages",
      nav_events: "Events",
      nav_gallery: "Gallery",
      nav_contact: "Contact",
      nav_my_bookings: "My Bookings",
      profile: "Profile",
      login: "Log in",
      logout: "Log out",
      register: "Sign up",
      book_now: "Book now",
      view_packages: "View packages",
      learn_more: "Details",
      book: "Book",
      contact_us: "Contact us",
      phone: "Phone",
      email: "Email",
      address: "Address",
      name: "Name",
      password: "Password",
      confirm_password: "Confirm password",
      submit: "Submit",
      booking_request: "Booking request",
      my_bookings_title: "My bookings",
      no_bookings: "No bookings yet.",
      booking_saved: "Your booking request has been received. Our staff will contact you soon.",
      login_required: "Please log in to make a booking.",
      welcome: "Welcome",
      have_account: "Already have an account? Log in",
      no_account: "No account? Sign up",
      hero_tagline: "Nature-close, comfortable retreat for you",
      service_rooms: "Rooms",
      service_food: "Dining",
      service_packages: "Packages",
      service_events: "Events",
      intro_label: "Introduction",
      intro_title: "A Comfortable Retreat in Nature",
      intro_text: "Monde Tour is a modern resort set among the forested hills and fresh air of Terelj. We blend the warm atmosphere of a traditional Mongolian ger with modern services, creating a relaxing experience for families, couples, friends, and corporate groups.",
      services_label: "Services",
      services_title: "What We Offer",
      services_desc: "Accommodation, dining, and events — all in one place",
      service_rooms_desc: "Ger, cabin, and shared room options",
      service_food_desc: "Traditional khorkhog and modern menu",
      service_packages_desc: "For families, couples, and companies",
      service_events_desc: "Weddings, team building, and celebrations",
      view_all_packages: "View all packages",
      packages_label: "Packages",
      packages_title: "Featured Packages",
      packages_desc: "Our most popular and best-value choices",
      view_all_rooms: "View all rooms",
      rooms_label: "Rooms",
      rooms_title: "Featured Rooms",
      rooms_desc: "Comfortable rooms in the heart of nature",
      events_label: "Events",
      events_title: "Plan Your Event",
      events_desc: "From corporate meetings to weddings — we are here to help",
      gallery_title: "The Look of Monde Tour",
      gallery_desc: "Highlights of nature, rooms, food, and events",
      view_all_gallery: "View all photos",
      location_title: "Location",
      location_find_title: "Find Us in Terelj",
      location_text: "Located 58 km from Ulaanbaatar in the scenic Terelj valley. Traffic is usually light, and the drive takes about 1–1.5 hours by car.",
      location_desc: "Located 58 km from Ulaanbaatar in the scenic Terelj valley.",
      philosophy_label: "Philosophy",
      philosophy_title: "What Makes Us Special",
      directions: "Get directions",
      coordinates: "Coordinates",
      contact_title: "Contact Us",
      contact_subtitle: "Get in touch and let us help plan your trip",
      send_message: "Send message",
      your_name: "Your name",
      your_email: "Email address",
      your_message: "Message",
      message_sent: "Message sent. Thank you!",
      follow_us: "Follow us",
      quick_links: "Quick links",
      newsletter: "Newsletter",
      subscribe: "Subscribe",
      gallery: "Gallery",
      view_map: "View map",
      rooms_page_title: "Rooms",
      rooms_page_desc: "Comfortable room options in the heart of nature",
      all_rooms: "All rooms",
      filter_rooms: "Filter rooms",
      sort_by: "Sort by",
      no_rooms: "No rooms found.",
      capacity: "Capacity",
      beds: "Beds",
      amenities: "Amenities",
      price_per_night: "Price per night",
      price_per_person: "Price per person",
      night: "night",
      person: "person",
      people: "People",
      details: "Details",
      room_detail_title: "Room Details",
      room_detail_desc: "Room information, price, and amenities",
      book_this_room: "Book this room",
      gallery_room: "Room gallery",
      food_page_title: "Dining",
      food_page_desc: "Traditional Mongolian dishes and modern menu",
      menu: "Menu",
      menu_category_all: "All",
      menu_category_mongolian: "Mongolian",
      menu_category_bbq: "BBQ",
      menu_category_beverage: "Beverages",
      menu_category_dessert: "Desserts",
      ingredients: "Ingredients",
      portion: "Portion",
      packages_page_title: "Packages",
      packages_page_desc: "Packages for families, couples, and companies",
      all_packages: "All packages",
      duration: "Duration",
      days: "days",
      package_detail_title: "Package Details",
      package_detail_desc: "Package program, price, and capacity",
      includes: "Includes",
      itinerary: "Itinerary",
      book_this_package: "Book this package",
      gallery_page_title: "Gallery",
      gallery_page_desc: "Highlights of nature, rooms, food, and events",
      all_photos: "All photos",
      category_nature: "Nature",
      category_rooms: "Rooms",
      category_food: "Food",
      category_events: "Events",
      category_people: "People",
      contact_page_title: "Contact",
      contact_page_desc: "Get in touch and let us help plan your trip",
      get_in_touch: "Get in touch",
      contact_info: "Contact information",
      opening_hours: "Opening hours",
      open_daily: "Open daily 08:00 - 22:00",
      booking_page_title: "Booking",
      booking_page_desc: "Book rooms, packages, and event services online",
      select_service: "Select service",
      arrival_date: "Arrival date",
      departure_date: "Departure date",
      select_room: "Select room",
      select_package: "Select package",
      notes: "Additional information",
      your_request: "Your request",
      my_bookings_page_title: "My Bookings",
      my_bookings_page_desc: "Your past and active bookings",
      booking_date: "Booking date",
      booking_status: "Status",
      auth_page_title: "Log in / Sign up",
      auth_page_desc: "Manage your profile and track bookings",
      phone_registered: "This phone number is already registered.",
      invalid_credentials: "Phone or password is incorrect.",
      password_mismatch: "Passwords do not match.",
      services: "Services",
      corporate_events: "Corporate events",
      weddings: "Weddings",
      family_celebrations: "Family celebrations",
      rights_reserved: "All rights reserved",
      admin: "Admin",
      close: "Close",
      menu_open: "Open menu",
      menu_close: "Close menu",
      admin_dashboard: "Dashboard",
      admin_bookings: "Bookings",
      admin_rooms: "Rooms",
      admin_packages: "Packages",
      admin_menu: "Menu",
      admin_events: "Events",
      admin_gallery: "Gallery",
      admin_settings: "Settings",
      back_to_site: "Back to site",
      admin_login_title: "Monde Tour Admin",
      admin_login_desc: "Enter your login credentials",
      admin_password: "Password",
      admin_default_password: "Default password",
      admin_total_rooms: "Total rooms",
      admin_total_packages: "Total packages",
      admin_new_bookings: "New bookings",
      admin_total_bookings: "Total bookings",
      admin_recent_bookings: "Recent bookings",
      admin_all_bookings: "All booking requests",
      admin_room_list: "Room list",
      admin_add_room: "Add room",
      admin_package_list: "Package list",
      admin_add_package: "Add package",
      admin_menu_list: "Menu",
      admin_add_menu: "Add dish",
      admin_event_list: "Event list",
      admin_add_event: "Add event",
      admin_gallery_list: "Gallery",
      admin_add_gallery: "Add photo",
      admin_general_settings: "General settings",
      admin_save: "Save",
      admin_reset_data: "Reset data",
      admin_no_bookings: "No bookings yet.",
      admin_status_updated: "Status updated.",
      admin_room_saved: "Room saved.",
      admin_room_deleted: "Room deleted.",
      admin_package_saved: "Package saved.",
      admin_package_deleted: "Package deleted.",
      admin_menu_saved: "Menu saved.",
      admin_menu_deleted: "Dish deleted.",
      admin_event_saved: "Event saved.",
      admin_event_deleted: "Event deleted.",
      admin_gallery_saved: "Photo saved.",
      admin_gallery_deleted: "Photo deleted.",
      admin_settings_saved: "Settings saved.",
      admin_delete_room_confirm: "Delete this room?",
      admin_delete_package_confirm: "Delete this package?",
      admin_delete_menu_confirm: "Delete this dish?",
      admin_delete_event_confirm: "Delete this event?",
      admin_delete_gallery_confirm: "Delete this photo?",
      admin_edit_room: "Edit room",
      admin_add_room_title: "Add new room",
      admin_edit_package: "Edit package",
      admin_add_package_title: "Add new package",
      admin_edit_menu: "Edit dish",
      admin_add_menu_title: "Add new dish",
      admin_edit_event: "Edit event",
      admin_add_event_title: "Add new event",
      admin_edit_gallery: "Edit photo",
      admin_add_gallery_title: "Add new photo",
      admin_delete: "Delete",
      edit: "Edit",
      featured: "Featured",
      cancel: "Cancel",
      save: "Save",
      type: "Type",
      category: "Category",
      description: "Description",
      title: "Title",
      image: "Image"
    }
  }
};

// Initialize localStorage if empty
function initData() {
  if (!localStorage.getItem('mondeTourData')) {
    localStorage.setItem('mondeTourData', JSON.stringify(defaultData));
  }
}

function getData() {
  initData();
  return JSON.parse(localStorage.getItem('mondeTourData'));
}

function saveData(data) {
  localStorage.setItem('mondeTourData', JSON.stringify(data));
}

function resetData() {
  localStorage.setItem('mondeTourData', JSON.stringify(defaultData));
}

// Format currency
function formatPrice(price) {
  if (price === 0) return 'Захиалгаар';
  return new Intl.NumberFormat('mn-MN').format(price) + ' ₮';
}

// Safe text escape
function escapeHtml(text) {
  const div = document.createElement('div');
  div.textContent = text;
  return div.innerHTML;
}
